Testing rocfft in CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,35 +5,45 @@ image: ubuntu:bionic
 
 before_script: &base_setup
     - apt-get update -qq
-    - apt-get install -yqq cmake make g++ clang
+    - apt-get install -yqq cmake make pkg-config g++ clang
     - apt-get install -yqq libboost-{program-options,filesystem,system,test}-dev
 
 .use_gcc: &use_gcc
-    CC: gcc
-    CXX: g++
+    CC: "gcc"
+    CXX: "g++"
 
 .use_clang: &use_clang
-    CC: clang
-    CXX: clang++
+    CC: "clang"
+    CXX: "clang++"
+
+.use_hipcc: &use_hipcc
+    CC: "clang"
+    CXX: "hipcc"
 
 .release_build: &release_build
-    GEARSHIFFT_BUILD_TYPE: Release
+    CMAKE_BUILD_TYPE: "Release"
+    CMAKE_VERBOSE_MAKEFILE: "Off"
+    GEARSHIFFT_VERBOSE: "Off"
 
 .debug_build: &debug_build
-    GEARSHIFFT_BUILD_TYPE: Debug
-
-.keep_build: &keep_build
-    paths:
-        - build
+    CMAKE_BUILD_TYPE: "Debug"
+    CMAKE_VERBOSE_MAKEFILE: "On"
+    GEARSHIFFT_VERBOSE: "On"
 
 .generic_build_and_test: &generic_build_and_test
-- mkdir build && cd build
-- cmake -DCMAKE_BUILD_TYPE=$GEARSHIFFT_BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE=ON ..
+- mkdir build
+- cd build
+- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE=$CMAKE_VERBOSE_MAKEFILE -DGEARSHIFFT_VERBOSE=$GEARSHIFFT_VERBOSE ..
 - make -j $(nproc)
-- ls -l
-- nproc
-- "export OMP_NUM_THREADS=$(($(nproc) < 4 ? $(nproc) : 4))"
 - make test
+
+.signal_test: &signal_test
+- sigs=(QUIT KILL TERM)   # don't send SIGABRT (is ignored by gearshifft)
+- for sig in "${sigs[@]}"; do
+    timeout -s "$sig" 10 ./gearshifft/gearshifft_fftw -e 16 32 64 128 256 512 -o out.csv &> /dev/null || true;
+    [[ $(wc -l < out.csv~) -gt 2 ]] && echo "Test successful for SIG$sig" || { echo "Test failed for SIG$sig" && false; };
+    rm out.csv*;
+  done
 
 fftw:
     stage: test
@@ -45,12 +55,7 @@ fftw:
         - apt-get install -yqq libfftw3-dev
     script:
         - *generic_build_and_test
-        - sigs=(QUIT KILL TERM)   # don't send SIGABRT (is ignored by gearshifft)
-        - for sig in "${sigs[@]}"; do
-              timeout -s "$sig" 10 ./gearshifft/gearshifft_fftw -e 16 32 64 128 256 512 -o myout.csv &> /dev/null || true;
-              [[ $(wc -l < myout.csv~) -gt 2 ]] && echo "Test successful for SIG$sig" || { echo "Test failed for SIG$sig" && false; };
-              rm myout.csv*;
-          done
+        - *signal_test
 
 fftw_debug:
     stage: test
@@ -98,5 +103,23 @@ clfft:
     before_script:
         - *base_setup
         - apt-get install -yqq libclfft-dev
+    script:
+        - *generic_build_and_test
+
+# TODO: Un-hide when this issue is resolved: https://github.com/RadeonOpenCompute/rocminfo/issues/38
+.rocfft:
+    stage: test
+    tags:
+        - amd
+        - rocm
+    image: rocm/dev-ubuntu-18.04
+    variables:
+        <<: *use_hipcc
+        <<: *debug_build
+    before_script:
+        - *base_setup
+        - apt-get install -yqq rocm-libs
+        - export PATH="/opt/rocm-3.8.0/bin:/opt/rocm-3.8.0/hip/bin:/opt/rocm-3.8.0/llvm/bin:$PATH"
+        - export CMAKE_PREFIX_PATH="$(echo /opt/rocm-*/lib/cmake/* /opt/rocm-*/hip/lib/cmake/* | tr ' ' ':')"
     script:
         - *generic_build_and_test
