Resolve "add a .gitlab-ci.yml based on .travis.yml"

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -92,6 +92,13 @@ script:
       make gearshifft
       cd gearshifft-build
       ctest --output-on-failure
+      sigs=(QUIT ABRT KILL TERM)
+      echo "Sending signals to gearshifft_fftw ..."
+      for sig in "${sigs[@]}"; do
+          timeout -s "$sig" 10 ./gearshifft_fftw -e 16 32 64 128 -o myout.csv || true
+          [[ $(wc -l < myout.csv~) -gt 2 ]] && echo "Test successful for SIG$sig" || { echo "Test failed for SIG$sig" && false; }
+          rm myout.csv*
+      done
     - set +e
 
 notifications:
